//! 跨模块**黄金表**：9 条手写 `Display`、每个公开枚举的变体（R48 两半）、
//! 每个公开类型的 trait 界面、每个公开常量的取值、派生 `Debug` 的诊断形状、
//! 以及整张流派登记表的**全字段逐条**表。
//!
//! ## 登记表四层防线（形态 D 第四～七批的实测收敛）
//!
//! 1. **求和**（第四批）：抓单条改动，怕抵消；
//! 2. **多重集直方图**（第五批）：抓抵消，怕互换；
//! 3. **5 字段逐条位置敏感表**（第六批）：抓互换，但只覆盖 `(id, BPM, 拍号, 密度, 摇摆千分比)`；
//! 4. **11 字段逐条全表**（本批）：`source` / `name_en` / `name_zh` / 两个列表的
//!    **全部元素** / `swing` 的**精确 f32 位型** —— 第七批实测第三层漏掉 **11/13**
//!    条改动（`source` 互换与单改、`name_en`/`name_zh` 互换与单改、两个列表的
//!    互换与**非首元素**改动、亚取整的 `swing` 改动、`None → Some(50.0)` 之外的
//!    `swing` 位型改动），本层把它们全部收口。
//!
//! ⚠ 注入纪律（R44①）：黄金表让被钉文本出现两次 ⇒ 注入一律**按行锚定生产代码**。

use yeban_theory::chord::{Chord, ChordKind, Tonality};
use yeban_theory::drum::{Backbeat, DRUM_VOICE_COUNT, DrumHit, DrumPattern, DrumStyle, DrumVoice};
use yeban_theory::error::TheoryError;
use yeban_theory::genre::{
    GenreLibrary, GenreRule, SOURCE_20C_COMMERCIAL_PRACTICE, SOURCE_COMMON_PRACTICE,
    SOURCE_TRADITIONAL_THEORY, SOURCE_YEBAN_ORIGINAL,
};
use yeban_theory::melody::{
    CHORD_TONE_WEIGHT_FLOOR, MELODY_LOWER_BOUND, MELODY_MAX_LEAP, MELODY_UPPER_BOUND, Melody,
    MelodyConstraints, MelodyNote,
};
use yeban_theory::pitch::{Interval, NoteName, Pitch, PitchClass, SpelledPitch};
use yeban_theory::progression::{
    ChordSpan, Degree, MIN_DURATION_TICKS, Meter, PPQ, Progression, RomanQuality,
};
use yeban_theory::rhythm::{
    BEAT_WEIGHT, BeatGrouping, GRID_CELL_TICKS, GridHit, MAX_METRIC_WEIGHT, MetricGrid,
    OFFBEAT_WEIGHT, STRONG_BEAT_WEIGHT, SWING_PAIR_TICKS,
};
use yeban_theory::scale::{Scale, ScaleKind};
use yeban_theory::swing::{SWING_PERMILLE_MAX, SWING_PERMILLE_STRAIGHT, SwingPair};
use yeban_theory::voice_leading::{VoiceLeadingResult, VoiceRange, VoicingConstraints};

// --------------------------------------------------------------------------
// 枚举的臂清单（R48 第一半：`arm` 函数没有通配臂 ⇒ 新增变体编译失败；
// 第二半：把清单经 `arm` 映射后断言恰为 `0..N` ⇒ 缺一臂/重复臂运行时红）。
// --------------------------------------------------------------------------

const ALL_CHORD_KINDS: [ChordKind; 21] = [
    ChordKind::Major,
    ChordKind::Minor,
    ChordKind::Diminished,
    ChordKind::Augmented,
    ChordKind::Sus2,
    ChordKind::Sus4,
    ChordKind::Six,
    ChordKind::Dominant7,
    ChordKind::Major7,
    ChordKind::Minor7,
    ChordKind::HalfDiminished7,
    ChordKind::Diminished7,
    ChordKind::MinorMajor7,
    ChordKind::Dominant9,
    ChordKind::Major9,
    ChordKind::Minor9,
    ChordKind::Dominant11,
    ChordKind::Dominant13,
    ChordKind::Add9,
    ChordKind::SixNine,
    ChordKind::Dominant7Sus4,
];
const ALL_TONALITIES: [Tonality; 3] = [Tonality::SharpMajor, Tonality::FlatMajor, Tonality::Minor];
const ALL_SCALE_KINDS: [ScaleKind; 16] = [
    ScaleKind::Major,
    ScaleKind::Ionian,
    ScaleKind::NaturalMinor,
    ScaleKind::Aeolian,
    ScaleKind::HarmonicMinor,
    ScaleKind::MelodicMinor,
    ScaleKind::Dorian,
    ScaleKind::Phrygian,
    ScaleKind::Lydian,
    ScaleKind::Mixolydian,
    ScaleKind::Locrian,
    ScaleKind::PentatonicMajor,
    ScaleKind::PentatonicMinor,
    ScaleKind::Blues,
    ScaleKind::WholeTone,
    ScaleKind::Chromatic,
];
const ALL_ROMAN_QUALITIES: [RomanQuality; 5] = [
    RomanQuality::Major,
    RomanQuality::Minor,
    RomanQuality::Diminished,
    RomanQuality::Augmented,
    RomanQuality::HalfDiminished,
];
const ALL_DRUM_VOICES: [DrumVoice; DRUM_VOICE_COUNT] = [
    DrumVoice::Kick,
    DrumVoice::Snare,
    DrumVoice::HiHat,
    DrumVoice::Ride,
];
const ALL_DRUM_STYLES: [DrumStyle; 2] = [DrumStyle::Metric, DrumStyle::FourOnTheFloor];

fn chord_kind_arm(kind: ChordKind) -> u8 {
    match kind {
        ChordKind::Major => 0,
        ChordKind::Minor => 1,
        ChordKind::Diminished => 2,
        ChordKind::Augmented => 3,
        ChordKind::Sus2 => 4,
        ChordKind::Sus4 => 5,
        ChordKind::Six => 6,
        ChordKind::Dominant7 => 7,
        ChordKind::Major7 => 8,
        ChordKind::Minor7 => 9,
        ChordKind::HalfDiminished7 => 10,
        ChordKind::Diminished7 => 11,
        ChordKind::MinorMajor7 => 12,
        ChordKind::Dominant9 => 13,
        ChordKind::Major9 => 14,
        ChordKind::Minor9 => 15,
        ChordKind::Dominant11 => 16,
        ChordKind::Dominant13 => 17,
        ChordKind::Add9 => 18,
        ChordKind::SixNine => 19,
        ChordKind::Dominant7Sus4 => 20,
    }
}
fn tonality_arm(tonality: Tonality) -> u8 {
    match tonality {
        Tonality::SharpMajor => 0,
        Tonality::FlatMajor => 1,
        Tonality::Minor => 2,
    }
}
fn scale_kind_arm(kind: ScaleKind) -> u8 {
    match kind {
        ScaleKind::Major => 0,
        ScaleKind::Ionian => 1,
        ScaleKind::NaturalMinor => 2,
        ScaleKind::Aeolian => 3,
        ScaleKind::HarmonicMinor => 4,
        ScaleKind::MelodicMinor => 5,
        ScaleKind::Dorian => 6,
        ScaleKind::Phrygian => 7,
        ScaleKind::Lydian => 8,
        ScaleKind::Mixolydian => 9,
        ScaleKind::Locrian => 10,
        ScaleKind::PentatonicMajor => 11,
        ScaleKind::PentatonicMinor => 12,
        ScaleKind::Blues => 13,
        ScaleKind::WholeTone => 14,
        ScaleKind::Chromatic => 15,
    }
}
fn roman_quality_arm(quality: RomanQuality) -> u8 {
    match quality {
        RomanQuality::Major => 0,
        RomanQuality::Minor => 1,
        RomanQuality::Diminished => 2,
        RomanQuality::Augmented => 3,
        RomanQuality::HalfDiminished => 4,
    }
}
fn drum_voice_arm(voice: DrumVoice) -> u8 {
    match voice {
        DrumVoice::Kick => 0,
        DrumVoice::Snare => 1,
        DrumVoice::HiHat => 2,
        DrumVoice::Ride => 3,
    }
}
fn drum_style_arm(style: DrumStyle) -> u8 {
    match style {
        DrumStyle::Metric => 0,
        DrumStyle::FourOnTheFloor => 1,
    }
}

/// R48 两半：`arm` 无通配臂（新增变体 ⇒ `error[E0004]` 编译失败）；
/// 清单经 `arm` 映射后必须恰为 `0..N`（缺一臂或有重复 ⇒ 运行时红）。
#[test]
fn enum_arm_tables_are_exhaustive_and_gap_free() {
    let arms: Vec<u8> = ALL_CHORD_KINDS.iter().map(|k| chord_kind_arm(*k)).collect();
    assert_eq!(arms, (0..21).collect::<Vec<u8>>(), "ChordKind arms");
    let arms: Vec<u8> = ALL_TONALITIES.iter().map(|t| tonality_arm(*t)).collect();
    assert_eq!(arms, (0..3).collect::<Vec<u8>>(), "Tonality arms");
    let arms: Vec<u8> = ALL_SCALE_KINDS.iter().map(|k| scale_kind_arm(*k)).collect();
    assert_eq!(arms, (0..16).collect::<Vec<u8>>(), "ScaleKind arms");
    let arms: Vec<u8> = ALL_ROMAN_QUALITIES
        .iter()
        .map(|q| roman_quality_arm(*q))
        .collect();
    assert_eq!(arms, (0..5).collect::<Vec<u8>>(), "RomanQuality arms");
    let arms: Vec<u8> = ALL_DRUM_VOICES.iter().map(|v| drum_voice_arm(*v)).collect();
    assert_eq!(arms, (0..4).collect::<Vec<u8>>(), "DrumVoice arms");
    let arms: Vec<u8> = ALL_DRUM_STYLES.iter().map(|s| drum_style_arm(*s)).collect();
    assert_eq!(arms, (0..2).collect::<Vec<u8>>(), "DrumStyle arms");
    // 清单长度必须等于臂数（表本身也要与臂一一对应）。
    assert_eq!(ALL_CHORD_KINDS.len(), 21);
    assert_eq!(ALL_SCALE_KINDS.len(), 16);
    assert_eq!(ALL_DRUM_VOICES.len(), DRUM_VOICE_COUNT);
}

/// 9 条手写 `Display`，每条一行。加一条 `Display` 而不加一行 ⇒ 长度断言变红。
#[test]
fn display_golden_table_covers_every_manual_display_impl() {
    let rendered: Vec<String> = vec![
        Chord::new(PitchClass::C, ChordKind::Major).to_string(),
        NoteName::new(6, 1).unwrap().to_string(),
        "C#4".parse::<SpelledPitch>().unwrap().to_string(),
        PitchClass::FS.to_string(),
        Pitch::C4.to_string(),
        Interval::PERFECT_FIFTH.to_string(),
        Degree::parse("bVII").unwrap().to_string(),
        Progression::parse("I-V-vi-IV").unwrap().to_string(),
        Scale::new(PitchClass::C, ScaleKind::Major).to_string(),
    ];
    assert_eq!(
        rendered.len(),
        9,
        "the crate has exactly 9 manual `Display` impls"
    );
    assert_eq!(
        rendered,
        vec![
            "C",
            "B#",
            "C#4",
            "F#",
            "C4",
            "P5",
            "bVII",
            "I-V-vi-IV",
            "C major"
        ]
    );
    assert_eq!(
        rendered[0],
        Chord::new(PitchClass::C, ChordKind::Major).symbol()
    );
    assert_eq!(rendered[5], Interval::PERFECT_FIFTH.name());
    assert_eq!(rendered[6], Degree::parse("bVII").unwrap().symbol());
    assert_eq!(
        rendered[8],
        format!("{} {}", PitchClass::C, ScaleKind::Major.name())
    );
}

/// 派生 `Debug` 的**诊断形状**：`assert_eq!` 失败消息与 MCP 故障文本都用 `{x:?}`，
/// 因此字段名/顺序/变体名是**可观测**的。本 crate **没有**手写 `impl Debug`
/// （普查：13 条手写 impl 里只有 `Display`×9 / `FromStr`×2 / `PartialEq` / `Eq`），
/// 所以这里钉的是**派生形状**。
#[test]
fn derived_debug_shapes_are_pinned() {
    assert_eq!(
        format!("{:?}", Meter::COMMON),
        "Meter { numerator: 4, denominator: 4 }"
    );
    assert_eq!(
        format!("{:?}", TheoryError::PitchOutOfRange { value: 200 }),
        "PitchOutOfRange { value: 200 }"
    );
    assert_eq!(
        format!("{:?}", TheoryError::SwingOutOfRange { value: 4 }),
        "SwingOutOfRange { value: 4 }"
    );
    assert_eq!(
        format!("{:?}", TheoryError::NoteNameUnknown),
        "NoteNameUnknown"
    );
    assert_eq!(format!("{:?}", PitchClass::FS), "PitchClass(6)");
    assert_eq!(format!("{:?}", Pitch::C4), "Pitch(60)");
    assert_eq!(
        format!("{:?}", NoteName::new(6, 1).unwrap()),
        "NoteName { letter: 6, alter: 1 }"
    );
    assert_eq!(
        format!("{:?}", "C#4".parse::<SpelledPitch>().unwrap()),
        "SpelledPitch { name: NoteName { letter: 0, alter: 1 }, octave: 4 }"
    );
    assert_eq!(
        format!("{:?}", Interval::PERFECT_FIFTH),
        "Interval { semitones: 7, name: \"P5\", consonant: true }"
    );
    assert_eq!(
        format!(
            "{:?}",
            SwingPair {
                first: 320,
                second: 160
            }
        ),
        "SwingPair { first: 320, second: 160 }"
    );
    assert_eq!(
        format!("{:?}", Degree::parse("bVII").unwrap()),
        "Degree { degree: 7, accidental: -1, quality: Major, suffix: None }"
    );
    assert_eq!(
        format!("{:?}", RomanQuality::HalfDiminished),
        "HalfDiminished"
    );
    assert_eq!(
        format!(
            "{:?}",
            Chord::with_tonality(PitchClass::AS, ChordKind::Minor7, Tonality::FlatMajor)
        ),
        "Chord { root: PitchClass(10), kind: Minor7, tonality: FlatMajor, bass: None }"
    );
    assert_eq!(
        format!("{:?}", Scale::new(PitchClass::C, ScaleKind::Major)),
        "Scale { tonic: PitchClass(0), kind: Major }"
    );
    assert_eq!(
        format!(
            "{:?}",
            GridHit {
                tick: 240,
                bar: 1,
                cell: 4,
                weight: 3
            }
        ),
        "GridHit { tick: 240, bar: 1, cell: 4, weight: 3 }"
    );
    assert_eq!(
        format!(
            "{:?}",
            DrumHit {
                voice: DrumVoice::Snare,
                tick: 960,
                bar: 0,
                cell: 4,
                beat: 1,
                weight: 3,
                accent: false
            }
        ),
        "DrumHit { voice: Snare, tick: 960, bar: 0, cell: 4, beat: 1, weight: 3, accent: false }"
    );
    assert_eq!(
        format!(
            "{:?}",
            MelodyNote {
                start_tick: 0,
                duration_ticks: 240,
                pitch: 60,
                bar: 0,
                cell: 0,
                weight: 8,
                chord_tone: true
            }
        ),
        "MelodyNote { start_tick: 0, duration_ticks: 240, pitch: 60, bar: 0, cell: 0, weight: 8, chord_tone: true }"
    );
    assert_eq!(
        format!(
            "{:?}",
            VoiceRange {
                lower: Pitch::C4,
                upper: Pitch::C5
            }
        ),
        "VoiceRange { lower: Pitch(60), upper: Pitch(72) }"
    );
    assert_eq!(format!("{:?}", 2 as Backbeat), "2");
    // 两个带 `Vec` 的类型：只钉形状前缀（内容是运行期数据）。
    assert!(format!("{:?}", MelodyConstraints::DEFAULT).starts_with("MelodyConstraints { lower: "));
    let _: Option<Melody> = None;
    let _: Option<DrumPattern> = None;
    let _: Option<MetricGrid> = None;
    let _: Option<Progression> = None;
    let _: Option<VoicingConstraints> = None;
    let _: Option<VoiceLeadingResult> = None;
    let _: Option<ChordSpan> = None;
    let _: Option<GenreRule> = None;
}

/// 公开常量的**取值**逐条钉住（数组比字面量数组 ⇒ 不是常量自比）。
#[test]
fn crate_constants_are_pinned_to_their_documented_values() {
    let ticks: [u64; 4] = [PPQ, MIN_DURATION_TICKS, GRID_CELL_TICKS, SWING_PAIR_TICKS];
    assert_eq!(ticks, [960u64, 240, 240, 480]);
    let weights: [u8; 4] = [
        MAX_METRIC_WEIGHT,
        STRONG_BEAT_WEIGHT,
        BEAT_WEIGHT,
        OFFBEAT_WEIGHT,
    ];
    assert_eq!(weights, [8u8, 3, 2, 1]);
    let swing: [u16; 2] = [SWING_PERMILLE_STRAIGHT, SWING_PERMILLE_MAX];
    assert_eq!(swing, [500u16, 1000]);
    let melody: [u8; 4] = [
        MELODY_LOWER_BOUND,
        MELODY_UPPER_BOUND,
        MELODY_MAX_LEAP,
        CHORD_TONE_WEIGHT_FLOOR,
    ];
    assert_eq!(melody, [48u8, 84, 12, 1]);
    let counts: [usize; 2] = [yeban_theory::voice_leading::SEARCH_BEAM, DRUM_VOICE_COUNT];
    assert_eq!(counts, [24usize, 4]);
    let grid_cell = GRID_CELL_TICKS;
    let min_duration = MIN_DURATION_TICKS;
    let swing_pair = SWING_PAIR_TICKS;
    assert_eq!(grid_cell, min_duration);
    assert_eq!(min_duration, PPQ / 4);
    assert_eq!(swing_pair, PPQ / 2);
    assert!(weights[0] > weights[1] && weights[1] > weights[2] && weights[2] > weights[3]);
    assert!(swing[1] > swing[0]);
    assert!(melody[0] < melody[1]);
}

/// 每个**公开类型**的 trait 界面都是编译期契约（本批把第六批的做法推广到全部
/// 32 个公开类型）：删掉任一 `derive` 或手写 impl ⇒ 本判据**编译失败**。
#[test]
fn every_public_type_keeps_its_trait_surface() {
    fn debug<T: core::fmt::Debug>() {}
    fn cp<T: Copy>() {}
    fn eq<T: Eq>() {}
    fn ord<T: Ord>() {}
    fn hash<T: core::hash::Hash>() {}
    fn send_sync<T: Send + Sync + 'static>() {}
    fn display<T: core::fmt::Display>() {}
    fn from_str<T: core::str::FromStr>() {}
    fn error<T: std::error::Error>() {}
    fn default<T: Default>() {}

    macro_rules! suite {
        ($($t:ty),* $(,)?) => { $( debug::<$t>(); eq::<$t>(); send_sync::<$t>(); )* };
    }
    suite!(
        ChordKind,
        Tonality,
        Chord,
        DrumVoice,
        DrumStyle,
        DrumHit,
        DrumPattern,
        TheoryError,
        GenreRule,
        MelodyConstraints,
        MelodyNote,
        Melody,
        NoteName,
        SpelledPitch,
        PitchClass,
        Pitch,
        Interval,
        Meter,
        RomanQuality,
        Degree,
        Progression,
        ChordSpan,
        GridHit,
        MetricGrid,
        ScaleKind,
        Scale,
        SwingPair,
        VoiceRange,
        VoicingConstraints,
        VoiceLeadingResult,
    );
    // `GenreLibrary` 是单元标记类型：有 `Debug`/`Copy`/`Default`，但**没有** `Eq`。
    debug::<GenreLibrary>();
    cp::<GenreLibrary>();
    default::<GenreLibrary>();
    // 具备 `Copy` 的 27 个。
    macro_rules! cps { ($($t:ty),* $(,)?) => { $( cp::<$t>(); )* }; }
    cps!(
        ChordKind,
        Tonality,
        Chord,
        DrumVoice,
        DrumStyle,
        DrumHit,
        TheoryError,
        GenreRule,
        GenreLibrary,
        MelodyConstraints,
        MelodyNote,
        NoteName,
        SpelledPitch,
        PitchClass,
        Pitch,
        Interval,
        Meter,
        RomanQuality,
        Degree,
        ChordSpan,
        BeatGrouping<'static>,
        GridHit,
        ScaleKind,
        Scale,
        SwingPair,
        VoiceRange,
        VoicingConstraints,
    );
    // 具备 `Ord` + `Hash` 的 20 个。
    macro_rules! ords { ($($t:ty),* $(,)?) => { $( ord::<$t>(); hash::<$t>(); )* }; }
    ords!(
        ChordKind,
        Tonality,
        Chord,
        DrumVoice,
        DrumStyle,
        DrumHit,
        MelodyNote,
        NoteName,
        SpelledPitch,
        PitchClass,
        Pitch,
        Interval,
        Meter,
        RomanQuality,
        Degree,
        GridHit,
        ScaleKind,
        Scale,
        SwingPair,
        VoiceRange,
    );
    // 9 条手写 `Display` ＋ 2 条 `FromStr` ＋ `TheoryError: Error` ＋ `SwingPair: Default`。
    macro_rules! disp { ($($t:ty),* $(,)?) => { $( display::<$t>(); )* }; }
    disp!(
        Chord,
        NoteName,
        SpelledPitch,
        PitchClass,
        Pitch,
        Interval,
        Degree,
        Progression,
        Scale
    );
    from_str::<Chord>();
    from_str::<SpelledPitch>();
    error::<TheoryError>();
    default::<SwingPair>();
}

/// 整张流派登记表的**全字段逐条、位置敏感**黄金表（第四层）。
///
/// 11 个字段：`id` / `name_en` / `name_zh` / `source` / 底鼓口径 / `swing` 的
/// **精确 f32 位型** / `(BPM 区间)` / `(拍号)` / `(密度区间)` / 走向列表 / 音阶列表。
type RegistryRow = (
    &'static str,
    &'static str,
    &'static str,
    &'static str,
    &'static str,
    Option<u32>,
    (u16, u16),
    (u8, u8),
    (u8, u8),
    &'static str,
    &'static str,
);

#[test]
fn registry_full_golden_table_closes_the_third_layer() {
    static TABLE: [RegistryRow; 182] = [
        (
            "gregorian_chant",
            "Gregorian chant",
            "格里高利圣咏",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (50, 76),
            (4, 4),
            (4, 12),
            "I-IV-I|I-vi-IV-I",
            "dorian|phrygian|mixolydian|ionian",
        ),
        (
            "renaissance_polyphony",
            "Renaissance polyphony",
            "文艺复兴复调",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (60, 88),
            (4, 4),
            (16, 40),
            "I-IV-V-I|I-vi-ii-V",
            "dorian|ionian|aeolian",
        ),
        (
            "baroque_chorale",
            "Baroque chorale",
            "巴洛克众赞歌",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (56, 84),
            (4, 4),
            (12, 32),
            "I-IV-V-I|I-ii-V-I|I-vi-ii-V-I",
            "major|natural_minor",
        ),
        (
            "baroque_fugue",
            "Baroque fugue",
            "巴洛克赋格",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (66, 104),
            (4, 4),
            (24, 64),
            "I-V-I|i-V-i|I-IV-V-I",
            "major|natural_minor|dorian",
        ),
        (
            "baroque_suite",
            "Baroque dance suite",
            "巴洛克组曲",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (72, 132),
            (3, 4),
            (16, 48),
            "I-V-I|i-VII-VI-VII|I-IV-V-I",
            "major|natural_minor",
        ),
        (
            "classical_sonata",
            "Classical sonata",
            "古典奏鸣曲",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (80, 132),
            (4, 4),
            (16, 48),
            "I-V-I|I-ii-V-I|I-IV-V-I",
            "major|natural_minor",
        ),
        (
            "classical_minuet",
            "Minuet",
            "小步舞曲",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (108, 132),
            (3, 4),
            (12, 32),
            "I-V-I|I-IV-V-I",
            "major|natural_minor",
        ),
        (
            "waltz",
            "Waltz",
            "圆舞曲",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (84, 180),
            (3, 4),
            (12, 36),
            "I-V-I|I-IV-V-I|i-VI-III-VII",
            "major|natural_minor",
        ),
        (
            "march",
            "March",
            "进行曲",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (100, 140),
            (2, 4),
            (8, 24),
            "I-IV-V-I|I-V-I",
            "major|natural_minor",
        ),
        (
            "romantic_lied",
            "Romantic Lied",
            "浪漫主义艺术歌曲",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (56, 96),
            (4, 4),
            (12, 36),
            "I-V-vi-IV|i-VI-III-VII|I-vi-ii-V",
            "major|natural_minor|harmonic_minor",
        ),
        (
            "nocturne",
            "Nocturne",
            "夜曲",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (52, 84),
            (4, 4),
            (16, 48),
            "I-vi-ii-V|i-VI-III-VII",
            "major|natural_minor|melodic_minor",
        ),
        (
            "etude",
            "Étude",
            "练习曲",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (80, 176),
            (4, 4),
            (32, 96),
            "I-IV-V-I|i-VII-VI-VII",
            "major|natural_minor|chromatic",
        ),
        (
            "impressionism",
            "Impressionism",
            "印象主义",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (54, 92),
            (4, 4),
            (16, 56),
            "I-ii-I|I-VI-II-V|i-III-VI-III",
            "whole_tone|pentatonic_major|lydian|dorian",
        ),
        (
            "impressionist_piano",
            "Impressionist piano",
            "印象派钢琴",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (50, 88),
            (4, 4),
            (20, 64),
            "I-IV-I|I-ii-V-I",
            "whole_tone|pentatonic_major|lydian",
        ),
        (
            "orchestral_film_score",
            "Orchestral film score",
            "管弦配乐",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (60, 140),
            (4, 4),
            (16, 64),
            "i-VI-III-VII|I-V-vi-IV|i-iv-VII-III",
            "natural_minor|harmonic_minor|dorian|aeolian",
        ),
        (
            "epic_trailer",
            "Epic trailer music",
            "史诗预告片配乐",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (70, 130),
            (4, 4),
            (16, 48),
            "i-VI-III-VII|i-iv-VI-VII",
            "natural_minor|harmonic_minor|phrygian",
        ),
        (
            "minimalism",
            "Minimalism",
            "极简主义",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (72, 160),
            (4, 4),
            (32, 128),
            "I-IV-I|i-VII-i",
            "major|natural_minor|pentatonic_major|dorian",
        ),
        (
            "hymn",
            "Hymn",
            "赞美诗",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (60, 92),
            (4, 4),
            (8, 24),
            "I-IV-I-V-I|I-vi-IV-V",
            "major|ionian",
        ),
        (
            "anthem",
            "Anthem",
            "颂歌",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (64, 108),
            (4, 4),
            (8, 28),
            "I-IV-V-I|I-V-vi-IV",
            "major",
        ),
        (
            "carol",
            "Carol",
            "圣诞颂歌",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (76, 132),
            (3, 4),
            (8, 24),
            "I-IV-V-I|I-vi-ii-V",
            "major|natural_minor",
        ),
        (
            "lullaby",
            "Lullaby",
            "摇篮曲",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (52, 80),
            (3, 4),
            (4, 16),
            "I-IV-V-I|I-V-I",
            "major|pentatonic_major",
        ),
        (
            "opera_aria",
            "Opera aria",
            "歌剧咏叹调",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (60, 104),
            (4, 4),
            (12, 48),
            "I-vi-ii-V|I-IV-V-I|i-VI-iv-V",
            "major|natural_minor|harmonic_minor",
        ),
        (
            "operetta",
            "Operetta",
            "轻歌剧",
            "traditional-theory/public-domain",
            "Metric",
            Some(0x42600000),
            (88, 152),
            (3, 4),
            (12, 36),
            "I-V-I|I-IV-V-I",
            "major",
        ),
        (
            "ballet",
            "Ballet score",
            "芭蕾配乐",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (64, 144),
            (4, 4),
            (16, 56),
            "I-IV-V-I|i-VI-III-VII",
            "major|natural_minor|harmonic_minor",
        ),
        (
            "passacaglia",
            "Passacaglia",
            "帕萨卡利亚",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (56, 88),
            (3, 4),
            (16, 48),
            "i-VII-VI-V|i-iv-VII-III",
            "natural_minor|harmonic_minor|dorian",
        ),
        (
            "chaconne",
            "Chaconne",
            "恰空",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (60, 96),
            (3, 4),
            (16, 56),
            "i-VII-VI-VII|i-iv-V-i",
            "natural_minor|harmonic_minor",
        ),
        (
            "toccata",
            "Toccata",
            "托卡塔",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (92, 152),
            (4, 4),
            (32, 128),
            "i-V-i|I-V-I",
            "natural_minor|harmonic_minor|major",
        ),
        (
            "prelude",
            "Prelude",
            "前奏曲",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (66, 120),
            (4, 4),
            (24, 96),
            "I-vi-ii-V-I|i-VII-VI-VII",
            "major|natural_minor|chromatic",
        ),
        (
            "sonatina",
            "Sonatina",
            "小奏鸣曲",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (88, 132),
            (4, 4),
            (16, 40),
            "I-V-I|I-ii-V-I",
            "major|natural_minor",
        ),
        (
            "jazz_swing",
            "Swing jazz",
            "摇摆爵士",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42840000),
            (120, 260),
            (4, 4),
            (8, 32),
            "ii-V-I|I-vi-ii-V",
            "major|dorian|mixolydian",
        ),
        (
            "big_band",
            "Big band",
            "大乐队",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42840000),
            (110, 220),
            (4, 4),
            (16, 48),
            "I-vi-ii-V|ii-V-I",
            "major|blues|mixolydian",
        ),
        (
            "bebop",
            "Bebop",
            "比博普",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42680000),
            (180, 320),
            (4, 4),
            (32, 128),
            "ii-V-I|I-vi-ii-V",
            "major|dorian|mixolydian|blues",
        ),
        (
            "hard_bop",
            "Hard bop",
            "硬博普",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42800000),
            (140, 260),
            (4, 4),
            (24, 96),
            "ii-V-I|i-iv-i|I-vi-ii-V",
            "blues|dorian|mixolydian|major",
        ),
        (
            "cool_jazz",
            "Cool jazz",
            "冷爵士",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42700000),
            (88, 180),
            (4, 4),
            (12, 48),
            "ii-V-I|I-vi-ii-V",
            "major|dorian|lydian",
        ),
        (
            "modal_jazz",
            "Modal jazz",
            "调式爵士",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42700000),
            (96, 200),
            (4, 4),
            (8, 32),
            "i-VII|i-iv|I-IV",
            "dorian|mixolydian|lydian|aeolian",
        ),
        (
            "free_jazz",
            "Free jazz",
            "自由爵士",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (80, 240),
            (4, 4),
            (32, 160),
            "i-VI|I-ii",
            "chromatic|whole_tone|locrian|blues",
        ),
        (
            "bossa_nova",
            "Bossa nova",
            "巴萨诺瓦",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42580000),
            (96, 140),
            (4, 4),
            (8, 32),
            "I-vi-ii-V|ii-V-I|i-VII-VI-VII",
            "major|dorian|natural_minor",
        ),
        (
            "latin_jazz",
            "Latin jazz",
            "拉丁爵士",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (120, 220),
            (4, 4),
            (16, 64),
            "ii-V-I|i-iv-V-i",
            "major|dorian|blues|mixolydian",
        ),
        (
            "smooth_jazz",
            "Smooth jazz",
            "顺畅爵士",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42580000),
            (80, 116),
            (4, 4),
            (8, 24),
            "ii-V-I|I-vi-ii-V",
            "major|dorian",
        ),
        (
            "jazz_waltz",
            "Jazz waltz",
            "爵士圆舞曲",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42780000),
            (120, 220),
            (3, 4),
            (12, 48),
            "ii-V-I|I-vi-ii-V",
            "major|dorian|melodic_minor",
        ),
        (
            "gypsy_jazz",
            "Gypsy jazz",
            "吉普赛爵士",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42840000),
            (140, 280),
            (4, 4),
            (24, 96),
            "ii-V-I|I-vi-ii-V|i-VII-VI-VII",
            "harmonic_minor|dorian|major|blues",
        ),
        (
            "ragtime",
            "Ragtime",
            "拉格泰姆",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (88, 140),
            (2, 4),
            (24, 80),
            "I-V-I|I-vi-ii-V",
            "major|chromatic",
        ),
        (
            "stride_piano",
            "Stride piano",
            "跨步钢琴",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42780000),
            (110, 200),
            (4, 4),
            (32, 96),
            "I-vi-ii-V|ii-V-I",
            "major|blues|chromatic",
        ),
        (
            "boogie_woogie",
            "Boogie-woogie",
            "布吉伍吉",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42780000),
            (100, 180),
            (4, 4),
            (32, 96),
            "I-IV-I-V-I|I-V-IV-I",
            "blues|major",
        ),
        (
            "blues",
            "Blues",
            "布鲁斯",
            "traditional-theory/public-domain",
            "Metric",
            Some(0x42800000),
            (60, 160),
            (4, 4),
            (8, 32),
            "I-IV-I-V-I|i-iv-i-V-i",
            "blues|pentatonic_minor|mixolydian",
        ),
        (
            "delta_blues",
            "Delta blues",
            "三角洲布鲁斯",
            "traditional-theory/public-domain",
            "Metric",
            Some(0x42680000),
            (58, 104),
            (4, 4),
            (4, 16),
            "I-IV-I-V-I|i-iv-i-V-i",
            "blues|pentatonic_minor",
        ),
        (
            "chicago_blues",
            "Chicago blues",
            "芝加哥布鲁斯",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42780000),
            (80, 160),
            (4, 4),
            (12, 48),
            "I-IV-I-V-I|I-IV-V-I",
            "blues|mixolydian|pentatonic_minor",
        ),
        (
            "jump_blues",
            "Jump blues",
            "跳跃布鲁斯",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42840000),
            (130, 220),
            (4, 4),
            (16, 64),
            "I-IV-I-V-I|I-vi-ii-V",
            "blues|major|mixolydian",
        ),
        (
            "blues_rock",
            "Blues rock",
            "布鲁斯摇滚",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42600000),
            (90, 170),
            (4, 4),
            (12, 40),
            "I-IV-V-I|i-iv-i",
            "blues|pentatonic_minor|mixolydian",
        ),
        (
            "gospel",
            "Gospel",
            "福音音乐",
            "common-practice/public-domain",
            "Metric",
            Some(0x42680000),
            (68, 140),
            (4, 4),
            (12, 48),
            "I-IV-I-V-I|I-vi-ii-V",
            "major|pentatonic_major|blues",
        ),
        (
            "spiritual",
            "Spiritual",
            "灵歌",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (60, 104),
            (4, 4),
            (6, 20),
            "I-IV-I-V-I|I-V-I",
            "major|pentatonic_major|blues",
        ),
        (
            "work_song",
            "Work song",
            "劳动号子",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (72, 132),
            (4, 4),
            (4, 16),
            "I-IV-I|i-iv-i",
            "pentatonic_minor|blues|major",
        ),
        (
            "field_holler",
            "Field holler",
            "田野呼喊",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (52, 92),
            (4, 4),
            (2, 10),
            "I-IV-I|i-iv-i",
            "blues|pentatonic_minor",
        ),
        (
            "soul",
            "Soul",
            "灵魂乐",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42600000),
            (72, 140),
            (4, 4),
            (12, 48),
            "I-IV-V-I|i-VI-III-VII|I-vi-ii-V",
            "major|pentatonic_minor|blues",
        ),
        (
            "motown",
            "Motown",
            "摩城",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (100, 148),
            (4, 4),
            (16, 48),
            "I-vi-ii-V|I-IV-V-I",
            "major|pentatonic_major",
        ),
        (
            "funk",
            "Funk",
            "放克",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (90, 130),
            (4, 4),
            (24, 96),
            "i-VII|I7-IV7|i-iv",
            "dorian|mixolydian|blues|pentatonic_minor",
        ),
        (
            "p_funk",
            "P-funk",
            "P 放克",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (96, 128),
            (4, 4),
            (24, 80),
            "i-VII|i-iv-VII",
            "dorian|mixolydian|blues",
        ),
        (
            "disco",
            "Disco",
            "迪斯科",
            "20c-commercial-practice-facts",
            "FourOnTheFloor",
            None,
            (112, 132),
            (4, 4),
            (24, 64),
            "i-VI-III-VII|I-vi-ii-V|i-iv-VII-III",
            "natural_minor|dorian|major",
        ),
        (
            "boogie",
            "Boogie",
            "布吉舞曲",
            "20c-commercial-practice-facts",
            "FourOnTheFloor",
            None,
            (108, 136),
            (4, 4),
            (24, 64),
            "i-VII|I-IV",
            "natural_minor|blues",
        ),
        (
            "contemporary_rnb",
            "Contemporary R&B",
            "当代 R&B",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42580000),
            (64, 104),
            (4, 4),
            (12, 48),
            "i-VII-VI-VII|I-vi-ii-V|ii-V-I",
            "natural_minor|major|dorian",
        ),
        (
            "neo_soul",
            "Neo soul",
            "新灵魂乐",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42600000),
            (68, 104),
            (4, 4),
            (16, 64),
            "ii-V-I|i-VII-VI-VII|I-vi-ii-V",
            "dorian|major|melodic_minor|blues",
        ),
        (
            "quiet_storm",
            "Quiet storm",
            "静夜风暴",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (60, 92),
            (4, 4),
            (8, 32),
            "I-vi-ii-V|ii-V-I",
            "major|dorian|natural_minor",
        ),
        (
            "doo_wop",
            "Doo-wop",
            "嘟喔普",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (76, 128),
            (4, 4),
            (8, 24),
            "I-vi-IV-V|I-vi-ii-V",
            "major",
        ),
        (
            "rock_and_roll",
            "Rock and roll",
            "摇滚乐",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42600000),
            (120, 200),
            (4, 4),
            (12, 40),
            "I-IV-V-I|I-vi-ii-V|I-V-vi-IV",
            "major|blues|pentatonic_major",
        ),
        (
            "rockabilly",
            "Rockabilly",
            "洛卡比里",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42680000),
            (140, 220),
            (4, 4),
            (16, 56),
            "I-IV-V-I|I-V-I",
            "major|blues|pentatonic_major",
        ),
        (
            "surf_rock",
            "Surf rock",
            "冲浪摇滚",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (120, 176),
            (4, 4),
            (16, 48),
            "I-IV-V-I|i-VII-VI-VII",
            "major|pentatonic_major|dorian",
        ),
        (
            "garage_rock",
            "Garage rock",
            "车库摇滚",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (120, 180),
            (4, 4),
            (16, 48),
            "I-IV-V|i-VII",
            "major|pentatonic_minor|blues",
        ),
        (
            "psychedelic_rock",
            "Psychedelic rock",
            "迷幻摇滚",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (76, 140),
            (4, 4),
            (16, 64),
            "i-VII-VI-VII|I-IV-V-I",
            "dorian|mixolydian|pentatonic_minor",
        ),
        (
            "progressive_rock",
            "Progressive rock",
            "前卫摇滚",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (70, 176),
            (7, 8),
            (24, 96),
            "i-VI-III-VII|I-vi-ii-V",
            "natural_minor|dorian|mixolydian|whole_tone",
        ),
        (
            "hard_rock",
            "Hard rock",
            "硬摇滚",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (100, 160),
            (4, 4),
            (16, 48),
            "i-VII-VI-VII|I-IV-V|i-iv-VII",
            "pentatonic_minor|natural_minor|blues",
        ),
        (
            "heavy_metal",
            "Heavy metal",
            "重金属",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (100, 180),
            (4, 4),
            (24, 96),
            "i-VII-VI-VII|i-iv-VII-III",
            "natural_minor|phrygian|pentatonic_minor",
        ),
        (
            "thrash_metal",
            "Thrash metal",
            "鞭击金属",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (160, 260),
            (4, 4),
            (32, 128),
            "i-VII-VI-V|i-iv-VII-III",
            "natural_minor|phrygian|locrian",
        ),
        (
            "death_metal",
            "Death metal",
            "死亡金属",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (140, 260),
            (4, 4),
            (48, 160),
            "i-VI-VII|i-iv-VII",
            "phrygian|locrian|harmonic_minor",
        ),
        (
            "black_metal",
            "Black metal",
            "黑金属",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (120, 240),
            (4, 4),
            (32, 128),
            "i-VI-VII|i-VII-VI",
            "natural_minor|phrygian|locrian",
        ),
        (
            "doom_metal",
            "Doom metal",
            "末日金属",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (50, 90),
            (4, 4),
            (8, 32),
            "i-VI-VII|i-iv-i",
            "natural_minor|phrygian|blues",
        ),
        (
            "power_metal",
            "Power metal",
            "力量金属",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (130, 200),
            (4, 4),
            (32, 128),
            "i-VI-III-VII|I-V-vi-IV",
            "natural_minor|harmonic_minor|major",
        ),
        (
            "progressive_metal",
            "Progressive metal",
            "前卫金属",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (90, 200),
            (7, 8),
            (32, 160),
            "i-VI-III-VII|i-iv-VII-III",
            "natural_minor|dorian|whole_tone|locrian",
        ),
        (
            "metalcore",
            "Metalcore",
            "金属核",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (130, 220),
            (4, 4),
            (32, 128),
            "i-VI-VII|i-iv-VII",
            "natural_minor|phrygian|blues",
        ),
        (
            "nu_metal",
            "Nu metal",
            "新金属",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (80, 140),
            (4, 4),
            (16, 64),
            "i-VII|i-iv",
            "natural_minor|phrygian|blues",
        ),
        (
            "punk_rock",
            "Punk rock",
            "朋克摇滚",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (140, 220),
            (4, 4),
            (16, 64),
            "I-IV-V|i-VII-VI-VII",
            "major|pentatonic_minor|blues",
        ),
        (
            "pop_punk",
            "Pop punk",
            "流行朋克",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (140, 200),
            (4, 4),
            (16, 64),
            "I-V-vi-IV|I-IV-V-I",
            "major|pentatonic_major",
        ),
        (
            "post_punk",
            "Post-punk",
            "后朋克",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (110, 170),
            (4, 4),
            (16, 48),
            "i-VII-VI-VII|i-iv",
            "natural_minor|dorian|phrygian",
        ),
        (
            "new_wave",
            "New wave",
            "新浪潮",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (110, 160),
            (4, 4),
            (16, 56),
            "I-V-vi-IV|i-VI-III-VII",
            "major|natural_minor|dorian",
        ),
        (
            "shoegaze",
            "Shoegaze",
            "自赏",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (76, 130),
            (4, 4),
            (16, 64),
            "I-IV|i-VI-III-VII",
            "major|dorian|lydian|pentatonic_major",
        ),
        (
            "grunge",
            "Grunge",
            "垃圾摇滚",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (80, 150),
            (4, 4),
            (12, 48),
            "i-VII-VI-VII|I-IV-V",
            "pentatonic_minor|natural_minor|blues",
        ),
        (
            "alternative_rock",
            "Alternative rock",
            "另类摇滚",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (90, 150),
            (4, 4),
            (16, 56),
            "i-VI-III-VII|I-V-vi-IV",
            "natural_minor|major|dorian",
        ),
        (
            "indie_rock",
            "Indie rock",
            "独立摇滚",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (96, 150),
            (4, 4),
            (16, 56),
            "I-V-vi-IV|I-vi-ii-V",
            "major|dorian|major",
        ),
        (
            "math_rock",
            "Math rock",
            "数学摇滚",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (110, 190),
            (7, 8),
            (32, 128),
            "I-IV|i-VI",
            "major|dorian|lydian|whole_tone",
        ),
        (
            "post_rock",
            "Post-rock",
            "后摇滚",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (60, 130),
            (4, 4),
            (16, 80),
            "I-IV-I|i-VI-III",
            "major|lydian|natural_minor|pentatonic_major",
        ),
        (
            "emo",
            "Emo",
            "情绪摇滚",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (110, 180),
            (4, 4),
            (16, 64),
            "I-V-vi-IV|i-VI-III-VII",
            "major|natural_minor|pentatonic_minor",
        ),
        (
            "house",
            "House",
            "浩室",
            "20c-commercial-practice-facts",
            "FourOnTheFloor",
            None,
            (118, 130),
            (4, 4),
            (16, 48),
            "i-VI-III-VII|i-iv-VII|I-vi-ii-V",
            "natural_minor|dorian|major",
        ),
        (
            "deep_house",
            "Deep house",
            "深度浩室",
            "20c-commercial-practice-facts",
            "FourOnTheFloor",
            None,
            (110, 125),
            (4, 4),
            (12, 40),
            "i-iv-VII-III|ii-V-I",
            "dorian|natural_minor|major",
        ),
        (
            "tech_house",
            "Tech house",
            "科技浩室",
            "20c-commercial-practice-facts",
            "FourOnTheFloor",
            None,
            (122, 130),
            (4, 4),
            (24, 64),
            "i-VII|i-iv",
            "natural_minor|phrygian|dorian",
        ),
        (
            "progressive_house",
            "Progressive house",
            "前卫浩室",
            "20c-commercial-practice-facts",
            "FourOnTheFloor",
            None,
            (124, 132),
            (4, 4),
            (16, 56),
            "i-VI-III-VII|i-VII-VI-VII",
            "natural_minor|dorian|aeolian",
        ),
        (
            "garage_house",
            "Garage house",
            "车库浩室",
            "20c-commercial-practice-facts",
            "FourOnTheFloor",
            Some(0x42600000),
            (120, 132),
            (4, 4),
            (16, 48),
            "i-VII-VI|ii-V-I",
            "natural_minor|dorian|major",
        ),
        (
            "techno",
            "Techno",
            "铁克诺",
            "20c-commercial-practice-facts",
            "FourOnTheFloor",
            None,
            (125, 150),
            (4, 4),
            (24, 96),
            "i-VII|i",
            "natural_minor|phrygian|chromatic",
        ),
        (
            "minimal_techno",
            "Minimal techno",
            "极简铁克诺",
            "20c-commercial-practice-facts",
            "FourOnTheFloor",
            None,
            (120, 132),
            (4, 4),
            (8, 32),
            "i|i-VII",
            "natural_minor|phrygian|chromatic",
        ),
        (
            "trance",
            "Trance",
            "迷幻舞曲",
            "20c-commercial-practice-facts",
            "FourOnTheFloor",
            None,
            (128, 145),
            (4, 4),
            (32, 128),
            "i-VI-III-VII|i-VII-VI-III",
            "natural_minor|harmonic_minor|dorian",
        ),
        (
            "psytrance",
            "Psytrance",
            "迷幻出神",
            "20c-commercial-practice-facts",
            "FourOnTheFloor",
            None,
            (138, 150),
            (4, 4),
            (48, 160),
            "i-VII|i-VI",
            "phrygian|natural_minor|harmonic_minor",
        ),
        (
            "hardstyle",
            "Hardstyle",
            "硬派",
            "20c-commercial-practice-facts",
            "FourOnTheFloor",
            None,
            (145, 160),
            (4, 4),
            (32, 96),
            "i-VI-III-VII|i-VII-VI",
            "natural_minor|harmonic_minor",
        ),
        (
            "dubstep",
            "Dubstep",
            "回响贝斯",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (138, 145),
            (4, 4),
            (16, 64),
            "i-VII|i-VI",
            "natural_minor|phrygian|blues",
        ),
        (
            "drum_and_bass",
            "Drum and bass",
            "鼓打贝斯",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (165, 180),
            (4, 4),
            (32, 128),
            "i-VII-VI|i-iv",
            "natural_minor|dorian|blues",
        ),
        (
            "jungle",
            "Jungle",
            "丛林",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (155, 175),
            (4, 4),
            (32, 160),
            "i-VII|i-iv",
            "natural_minor|dorian|blues",
        ),
        (
            "breakbeat",
            "Breakbeat",
            "碎拍",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (120, 145),
            (4, 4),
            (24, 96),
            "i-VII|I-IV",
            "natural_minor|mixolydian|blues",
        ),
        (
            "big_beat",
            "Big beat",
            "大节拍",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (120, 140),
            (4, 4),
            (32, 128),
            "i-VII|i-iv",
            "natural_minor|mixolydian|blues",
        ),
        (
            "trip_hop",
            "Trip hop",
            "神游舞曲",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (75, 100),
            (4, 4),
            (8, 32),
            "i-VI-III-VII|i-iv-VII",
            "natural_minor|dorian|pentatonic_minor",
        ),
        (
            "downtempo",
            "Downtempo",
            "缓拍",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (70, 110),
            (4, 4),
            (8, 32),
            "i-VII-VI|I-vi-ii-V",
            "dorian|natural_minor|major",
        ),
        (
            "ambient",
            "Ambient",
            "氛围",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (50, 90),
            (4, 4),
            (2, 16),
            "I|i-VI",
            "lydian|dorian|pentatonic_major|whole_tone",
        ),
        (
            "drone",
            "Drone",
            "持续音",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (40, 76),
            (4, 4),
            (1, 8),
            "I|i",
            "dorian|phrygian|lydian",
        ),
        (
            "new_age",
            "New age",
            "新世纪",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (56, 92),
            (4, 4),
            (8, 32),
            "I-IV-I|I-vi-IV",
            "major|lydian|pentatonic_major",
        ),
        (
            "synthwave",
            "Synthwave",
            "合成器浪潮",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (80, 118),
            (4, 4),
            (16, 64),
            "i-VI-III-VII|i-VII-VI-VII",
            "natural_minor|harmonic_minor|aeolian",
        ),
        (
            "vaporwave",
            "Vaporwave",
            "蒸汽波",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (60, 90),
            (4, 4),
            (8, 32),
            "I-vi-ii-V|ii-V-I",
            "major|dorian|lydian",
        ),
        (
            "lo_fi_hip_hop",
            "Lo-fi hip hop",
            "低保真嘻哈",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42600000),
            (70, 95),
            (4, 4),
            (8, 32),
            "ii-V-I|i-VI-III-VII|I-vi-ii-V",
            "dorian|major|natural_minor",
        ),
        (
            "boom_bap",
            "Boom bap",
            "布姆巴普",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42680000),
            (85, 100),
            (4, 4),
            (8, 32),
            "i-VII|i-iv",
            "natural_minor|dorian|pentatonic_minor",
        ),
        (
            "trap",
            "Trap",
            "陷阱音乐",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (130, 150),
            (4, 4),
            (16, 96),
            "i-VI|i-VII-VI",
            "natural_minor|harmonic_minor|phrygian",
        ),
        (
            "drill",
            "Drill",
            "德里尔",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (138, 150),
            (4, 4),
            (16, 96),
            "i-VI|i-VII",
            "natural_minor|harmonic_minor|phrygian",
        ),
        (
            "grime",
            "Grime",
            "格兰姆",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (138, 142),
            (4, 4),
            (24, 96),
            "i-VII|i-iv",
            "natural_minor|phrygian|chromatic",
        ),
        (
            "chiptune",
            "Chiptune",
            "芯片音乐",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (110, 180),
            (4, 4),
            (32, 128),
            "I-V-vi-IV|I-IV-V-I",
            "major|natural_minor|pentatonic_major",
        ),
        (
            "video_game_score",
            "Video game score",
            "电子游戏配乐",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (90, 176),
            (4, 4),
            (24, 96),
            "I-V-vi-IV|i-VI-III-VII",
            "major|natural_minor|lydian|dorian",
        ),
        (
            "pop",
            "Pop",
            "流行",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (90, 130),
            (4, 4),
            (12, 48),
            "I-V-vi-IV|I-vi-IV-V|vi-IV-I-V",
            "major|natural_minor",
        ),
        (
            "dance_pop",
            "Dance pop",
            "舞曲流行",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (110, 128),
            (4, 4),
            (16, 64),
            "I-V-vi-IV|i-VI-III-VII",
            "major|natural_minor",
        ),
        (
            "synth_pop",
            "Synth-pop",
            "合成器流行",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (100, 140),
            (4, 4),
            (16, 64),
            "I-V-vi-IV|i-VI-III-VII",
            "major|natural_minor|dorian",
        ),
        (
            "ballad",
            "Ballad",
            "民谣抒情曲",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (60, 88),
            (4, 4),
            (6, 24),
            "I-vi-IV-V|I-V-vi-IV|ii-V-I",
            "major|natural_minor",
        ),
        (
            "power_ballad",
            "Power ballad",
            "力量抒情曲",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (64, 92),
            (4, 4),
            (8, 32),
            "I-V-vi-IV|i-VI-III-VII",
            "major|natural_minor",
        ),
        (
            "folk",
            "Folk",
            "民谣",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (80, 140),
            (4, 4),
            (6, 24),
            "I-IV-V-I|I-V-I",
            "major|mixolydian|dorian|pentatonic_major",
        ),
        (
            "americana",
            "Americana",
            "美式民谣",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (76, 132),
            (4, 4),
            (8, 32),
            "I-IV-V-I|I-vi-ii-V",
            "major|mixolydian|pentatonic_major",
        ),
        (
            "country",
            "Country",
            "乡村",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42600000),
            (80, 140),
            (4, 4),
            (8, 32),
            "I-IV-V-I|I-V-vi-IV|I-vi-ii-V",
            "major|pentatonic_major|mixolydian",
        ),
        (
            "bluegrass",
            "Bluegrass",
            "蓝草",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (110, 180),
            (4, 4),
            (32, 96),
            "I-IV-V-I|I-V-I",
            "major|pentatonic_major|blues",
        ),
        (
            "honky_tonk",
            "Honky tonk",
            "酒馆乡村",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42680000),
            (100, 150),
            (4, 4),
            (16, 48),
            "I-IV-V-I|I-V-I",
            "major|blues|pentatonic_major",
        ),
        (
            "outlaw_country",
            "Outlaw country",
            "亡命乡村",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42600000),
            (84, 136),
            (4, 4),
            (8, 32),
            "I-IV-V-I|I-vi-ii-V",
            "major|mixolydian",
        ),
        (
            "celtic",
            "Celtic",
            "凯尔特",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (90, 160),
            (6, 8),
            (24, 96),
            "i-VII-VI-VII|I-IV-I-V",
            "dorian|mixolydian|aeolian|pentatonic_minor",
        ),
        (
            "irish_trad",
            "Irish traditional",
            "爱尔兰传统",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (100, 180),
            (6, 8),
            (24, 96),
            "i-VII-VI-VII|I-IV-V-I",
            "dorian|mixolydian|ionian|aeolian",
        ),
        (
            "jig",
            "Jig",
            "吉格舞曲",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (110, 160),
            (6, 8),
            (24, 72),
            "i-VII-VI-VII|I-IV-V-I",
            "dorian|mixolydian|aeolian",
        ),
        (
            "reel",
            "Reel",
            "里尔舞曲",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (130, 200),
            (4, 4),
            (32, 96),
            "i-VII-VI-VII|I-IV-V-I",
            "dorian|mixolydian|ionian",
        ),
        (
            "scottish_trad",
            "Scottish traditional",
            "苏格兰传统",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (90, 160),
            (4, 4),
            (24, 72),
            "I-IV-I-V|i-VII-VI-VII",
            "mixolydian|dorian|pentatonic_major",
        ),
        (
            "klezmer",
            "Klezmer",
            "克莱兹梅尔",
            "traditional-theory/public-domain",
            "Metric",
            Some(0x42600000),
            (90, 160),
            (4, 4),
            (16, 64),
            "i-VII-VI-V|i-iv-VII-III",
            "phrygian|harmonic_minor|dorian",
        ),
        (
            "balkan",
            "Balkan",
            "巴尔干",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (110, 180),
            (7, 8),
            (24, 96),
            "i-VII-VI-VII|i-iv-VII",
            "phrygian|harmonic_minor|dorian",
        ),
        (
            "polka",
            "Polka",
            "波尔卡",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (110, 150),
            (2, 4),
            (16, 48),
            "I-IV-V-I|I-V-I",
            "major",
        ),
        (
            "chanson",
            "Chanson",
            "法国香颂",
            "traditional-theory/public-domain",
            "Metric",
            Some(0x42600000),
            (76, 140),
            (3, 4),
            (8, 32),
            "i-VI-III-VII|I-vi-ii-V",
            "major|natural_minor|harmonic_minor",
        ),
        (
            "fado",
            "Fado",
            "法多",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (60, 100),
            (4, 4),
            (8, 32),
            "i-VII-VI-VII|i-iv-V-i",
            "natural_minor|harmonic_minor|phrygian",
        ),
        (
            "cabaret",
            "Cabaret",
            "卡巴莱",
            "20c-commercial-practice-facts",
            "Metric",
            Some(0x42680000),
            (88, 150),
            (4, 4),
            (12, 48),
            "I-vi-ii-V|i-VI-III-VII",
            "major|natural_minor",
        ),
        (
            "music_hall",
            "Music hall",
            "杂耍剧场",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (100, 160),
            (4, 4),
            (12, 40),
            "I-IV-V-I|I-V-I",
            "major",
        ),
        (
            "samba",
            "Samba",
            "桑巴",
            "common-practice/public-domain",
            "Metric",
            None,
            (90, 130),
            (2, 4),
            (32, 96),
            "I-vi-ii-V|i-VII-VI-VII",
            "major|dorian|natural_minor",
        ),
        (
            "bossa_nova_brazil",
            "Brazilian bossa nova",
            "巴西巴萨诺瓦",
            "common-practice/public-domain",
            "Metric",
            Some(0x42580000),
            (100, 136),
            (4, 4),
            (16, 56),
            "I-vi-ii-V|i-VII-VI-VII",
            "major|dorian|melodic_minor",
        ),
        (
            "choro",
            "Choro",
            "肖罗",
            "common-practice/public-domain",
            "Metric",
            None,
            (110, 160),
            (2, 4),
            (32, 128),
            "I-vi-ii-V|i-VII-VI-V",
            "major|harmonic_minor|dorian",
        ),
        (
            "tango",
            "Tango",
            "探戈",
            "common-practice/public-domain",
            "Metric",
            None,
            (60, 120),
            (4, 4),
            (12, 48),
            "i-VII-VI-V|i-iv-V-i",
            "natural_minor|harmonic_minor|phrygian",
        ),
        (
            "milonga",
            "Milonga",
            "米隆加",
            "common-practice/public-domain",
            "Metric",
            None,
            (90, 130),
            (2, 4),
            (16, 48),
            "i-VII-VI-V|i-iv-V-i",
            "natural_minor|harmonic_minor|dorian",
        ),
        (
            "bolero",
            "Bolero",
            "波莱罗情歌",
            "common-practice/public-domain",
            "Metric",
            None,
            (60, 96),
            (4, 4),
            (8, 32),
            "i-VI-III-VII|I-vi-ii-V",
            "natural_minor|major",
        ),
        (
            "son_cubano",
            "Son cubano",
            "古巴颂",
            "common-practice/public-domain",
            "Metric",
            None,
            (90, 140),
            (4, 4),
            (16, 64),
            "I-IV-V-I|i-VII-VI-VII",
            "major|dorian|natural_minor",
        ),
        (
            "salsa",
            "Salsa",
            "萨尔萨",
            "common-practice/public-domain",
            "Metric",
            None,
            (150, 220),
            (4, 4),
            (24, 96),
            "i-VII-VI-VII|I-IV-V-I",
            "natural_minor|major|dorian",
        ),
        (
            "merengue",
            "Merengue",
            "梅伦格",
            "common-practice/public-domain",
            "Metric",
            None,
            (120, 180),
            (2, 4),
            (24, 80),
            "I-IV-V-I|I-V-I",
            "major|natural_minor",
        ),
        (
            "bachata",
            "Bachata",
            "巴恰塔",
            "common-practice/public-domain",
            "Metric",
            None,
            (110, 150),
            (4, 4),
            (16, 64),
            "i-VII-VI-VII|I-IV-V-I",
            "natural_minor|major",
        ),
        (
            "cumbia",
            "Cumbia",
            "昆比亚",
            "common-practice/public-domain",
            "Metric",
            None,
            (85, 120),
            (4, 4),
            (16, 64),
            "i-VII-VI-VII|I-IV-V-I",
            "natural_minor|major|pentatonic_minor",
        ),
        (
            "reggaeton",
            "Reggaeton",
            "雷击顿",
            "20c-commercial-practice-facts",
            "Metric",
            None,
            (88, 100),
            (4, 4),
            (16, 64),
            "i-VI-III-VII|i-VII-VI",
            "natural_minor|harmonic_minor",
        ),
        (
            "mariachi",
            "Mariachi",
            "玛利亚奇",
            "common-practice/public-domain",
            "Metric",
            None,
            (90, 150),
            (3, 4),
            (12, 48),
            "I-IV-V-I|I-V-I",
            "major|natural_minor",
        ),
        (
            "ranchera",
            "Ranchera",
            "兰切拉",
            "common-practice/public-domain",
            "Metric",
            None,
            (70, 130),
            (3, 4),
            (8, 32),
            "I-IV-V-I|i-VII-VI-VII",
            "major|natural_minor",
        ),
        (
            "norteno",
            "Norteño",
            "北方音乐",
            "common-practice/public-domain",
            "Metric",
            None,
            (100, 150),
            (2, 4),
            (16, 56),
            "I-IV-V-I|I-V-I",
            "major|mixolydian",
        ),
        (
            "tejano",
            "Tejano",
            "特哈诺",
            "common-practice/public-domain",
            "Metric",
            None,
            (100, 150),
            (4, 4),
            (16, 56),
            "I-IV-V-I|i-VII-VI-VII",
            "major|natural_minor",
        ),
        (
            "flamenco",
            "Flamenco",
            "弗拉门戈",
            "common-practice/public-domain",
            "Metric",
            None,
            (90, 220),
            (4, 4),
            (24, 128),
            "i-VII-VI-V|i-iv-V-i|i-VI-VII-i",
            "phrygian|harmonic_minor|natural_minor",
        ),
        (
            "sevillanas",
            "Sevillanas",
            "塞维亚纳斯",
            "common-practice/public-domain",
            "Metric",
            None,
            (120, 180),
            (3, 4),
            (16, 56),
            "i-VII-VI-VII|I-IV-V-I",
            "phrygian|major|natural_minor",
        ),
        (
            "rumba_flamenca",
            "Rumba flamenca",
            "弗拉门戈伦巴",
            "common-practice/public-domain",
            "Metric",
            None,
            (100, 160),
            (4, 4),
            (24, 80),
            "i-VII-VI-VII|i-iv-VII",
            "phrygian|natural_minor|harmonic_minor",
        ),
        (
            "ska",
            "Ska",
            "斯卡",
            "common-practice/public-domain",
            "Metric",
            None,
            (120, 180),
            (4, 4),
            (24, 80),
            "I-IV-V-I|I-vi-ii-V",
            "major|natural_minor|blues",
        ),
        (
            "rocksteady",
            "Rocksteady",
            "慢摇",
            "common-practice/public-domain",
            "Metric",
            None,
            (76, 110),
            (4, 4),
            (12, 40),
            "I-vi-ii-V|i-VII-VI-VII",
            "major|natural_minor",
        ),
        (
            "reggae",
            "Reggae",
            "雷鬼",
            "common-practice/public-domain",
            "Metric",
            None,
            (60, 96),
            (4, 4),
            (8, 32),
            "I-IV-V-I|i-VII-VI-VII|I-vi-ii-V",
            "major|natural_minor|pentatonic_minor",
        ),
        (
            "dub",
            "Dub",
            "回响",
            "common-practice/public-domain",
            "Metric",
            None,
            (60, 100),
            (4, 4),
            (4, 24),
            "i-VII|i-VI-III-VII",
            "natural_minor|dorian|pentatonic_minor",
        ),
        (
            "dancehall",
            "Dancehall",
            "舞厅雷鬼",
            "common-practice/public-domain",
            "Metric",
            None,
            (90, 120),
            (4, 4),
            (16, 64),
            "i-VII-VI-VII|i-VI",
            "natural_minor|pentatonic_minor",
        ),
        (
            "afrobeat",
            "Afrobeat",
            "非洲节拍",
            "common-practice/public-domain",
            "Metric",
            None,
            (95, 130),
            (4, 4),
            (32, 128),
            "i-VII|i-iv-VII",
            "dorian|natural_minor|pentatonic_minor",
        ),
        (
            "highlife",
            "Highlife",
            "海莱夫",
            "common-practice/public-domain",
            "Metric",
            None,
            (100, 150),
            (4, 4),
            (24, 80),
            "I-IV-V-I|I-vi-ii-V",
            "major|pentatonic_major",
        ),
        (
            "soukous",
            "Soukous",
            "苏库斯",
            "common-practice/public-domain",
            "Metric",
            None,
            (120, 180),
            (4, 4),
            (32, 128),
            "I-IV-V-I|i-VII-VI-VII",
            "major|dorian|pentatonic_major",
        ),
        (
            "amapiano",
            "Amapiano",
            "阿玛皮亚诺",
            "20c-commercial-practice-facts",
            "FourOnTheFloor",
            None,
            (108, 118),
            (4, 4),
            (16, 64),
            "i-VII-VI|i-VI-III-VII",
            "natural_minor|dorian",
        ),
        (
            "afro_cuban",
            "Afro-Cuban",
            "非洲古巴",
            "common-practice/public-domain",
            "Metric",
            None,
            (100, 180),
            (4, 4),
            (24, 96),
            "i-VII-VI-VII|I-IV-V-I",
            "natural_minor|dorian|major",
        ),
        (
            "raita",
            "Gnawa",
            "拉伊塔",
            "common-practice/public-domain",
            "Metric",
            None,
            (90, 140),
            (4, 4),
            (24, 96),
            "i-VII|i-iv",
            "phrygian|natural_minor|pentatonic_minor",
        ),
        (
            "arabic_maqam",
            "Arabic maqam",
            "阿拉伯木卡姆",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (70, 160),
            (4, 4),
            (12, 64),
            "i-VII-VI-V|i-iv-V-i",
            "phrygian|harmonic_minor|dorian",
        ),
        (
            "turkish_makam",
            "Turkish makam",
            "土耳其马卡姆",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (70, 160),
            (4, 4),
            (12, 64),
            "i-VII-VI-V|i-iv-V-i",
            "phrygian|harmonic_minor|dorian",
        ),
        (
            "persian_dastgah",
            "Persian dastgah",
            "波斯达斯特加赫",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (60, 140),
            (4, 4),
            (8, 48),
            "i-VII-VI-V|i-iv-i",
            "phrygian|harmonic_minor|dorian",
        ),
        (
            "hindustani",
            "Hindustani classical",
            "印度斯坦古典",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (50, 180),
            (4, 4),
            (8, 96),
            "I|i-VII-VI-VII",
            "dorian|mixolydian|aeolian|phrygian",
        ),
        (
            "carnatic",
            "Carnatic classical",
            "卡纳提克古典",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (60, 180),
            (4, 4),
            (16, 96),
            "I|i-VII-VI-VII",
            "dorian|mixolydian|aeolian",
        ),
        (
            "bollywood",
            "Bollywood",
            "宝莱坞",
            "common-practice/public-domain",
            "Metric",
            None,
            (80, 150),
            (4, 4),
            (24, 96),
            "i-VI-III-VII|I-IV-V-I",
            "harmonic_minor|dorian|major|pentatonic_major",
        ),
        (
            "bhangra",
            "Bhangra",
            "邦格拉",
            "common-practice/public-domain",
            "Metric",
            None,
            (100, 160),
            (4, 4),
            (32, 128),
            "i-VII|I-IV-V-I",
            "mixolydian|dorian|pentatonic_major",
        ),
        (
            "gamelan",
            "Gamelan",
            "甘美兰",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (50, 100),
            (4, 4),
            (16, 64),
            "I|I-IV",
            "pentatonic_major|pentatonic_minor",
        ),
        (
            "pentatonic_east_asian",
            "East Asian pentatonic",
            "东亚五声",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (56, 120),
            (4, 4),
            (8, 40),
            "I-IV-I|I-V-I",
            "pentatonic_major|pentatonic_minor",
        ),
        (
            "andean",
            "Andean",
            "安第斯",
            "traditional-theory/public-domain",
            "Metric",
            None,
            (80, 140),
            (4, 4),
            (16, 64),
            "i-VII-VI-VII|i-iv-VII",
            "natural_minor|pentatonic_minor|dorian",
        ),
    ];
    let rules = GenreLibrary::all();
    assert_eq!(rules.len(), TABLE.len(), "the registry size changed");
    for (index, row) in TABLE.iter().enumerate() {
        let (id, name_en, name_zh, source, style, swing_bits, bpm, meter, density, progs, scales) =
            row;
        let rule = &rules[index];
        assert_eq!(rule.id, *id, "entry {index}: id");
        assert_eq!(rule.name_en, *name_en, "{}: name_en", rule.id);
        assert_eq!(rule.name_zh, *name_zh, "{}: name_zh", rule.id);
        assert_eq!(rule.source, *source, "{}: source", rule.id);
        assert_eq!(
            match rule.drum_style {
                DrumStyle::Metric => "Metric",
                DrumStyle::FourOnTheFloor => "FourOnTheFloor",
            },
            *style,
            "{}: drum_style",
            rule.id
        );
        assert_eq!(
            rule.swing.map(f32::to_bits),
            *swing_bits,
            "{}: swing f32 bit pattern",
            rule.id
        );
        assert_eq!(rule.default_bpm_range, *bpm, "{}: BPM", rule.id);
        assert_eq!(rule.meter, *meter, "{}: meter", rule.id);
        assert_eq!(rule.note_density_hint, *density, "{}: density", rule.id);
        assert_eq!(
            rule.typical_progressions.join("|"),
            *progs,
            "{}: typical_progressions",
            rule.id
        );
        assert_eq!(
            rule.typical_scales.join("|"),
            *scales,
            "{}: typical_scales",
            rule.id
        );
    }
    // 四层互相对账（求和 / 多重集 / 位置 / 全字段）。
    assert_eq!(TABLE.iter().map(|r| u32::from(r.6.0)).sum::<u32>(), 16814);
    assert_eq!(TABLE.iter().map(|r| u32::from(r.8.0)).sum::<u32>(), 3159);
    assert_eq!(TABLE.iter().filter(|r| r.5.is_some()).count(), 34);
    assert_eq!(TABLE.iter().filter(|r| r.4 == "FourOnTheFloor").count(), 13);
    assert_eq!(
        TABLE
            .iter()
            .filter(|r| r.3 == "traditional-theory/public-domain")
            .count(),
        52
    );
    assert_eq!(
        TABLE
            .iter()
            .filter(|r| r.3 == "common-practice/public-domain")
            .count(),
        31
    );
    assert_eq!(TABLE[0].0, "gregorian_chant");
}

/// 4 个 `SOURCE_*` 常量的**取值**逐条钉住（登记表里用的是字面量，因此这一条与
/// 上面那张表互补：表钉"每条用了哪个值"，本条钉"这些值本身是什么"）。
#[test]
fn source_constants_are_pinned_to_their_documented_values() {
    let sources: [&str; 4] = [
        SOURCE_TRADITIONAL_THEORY,
        SOURCE_COMMON_PRACTICE,
        SOURCE_20C_COMMERCIAL_PRACTICE,
        SOURCE_YEBAN_ORIGINAL,
    ];
    assert_eq!(
        sources,
        [
            "traditional-theory/public-domain",
            "common-practice/public-domain",
            "20c-commercial-practice-facts",
            "yeban-original-encoding",
        ]
    );
    // 四个取值两两不同（`source_histogram` 的键因此无歧义）。
    for (i, a) in sources.iter().enumerate() {
        for b in &sources[i + 1..] {
            assert_ne!(a, b);
        }
    }
}
